# Generated by Django 2.2 on 2020-11-18 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg_app', '0002_messagepost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagepost',
            old_name='contents',
            new_name='content',
        ),
    ]
