# Generated by Django 2.2 on 2020-11-19 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_reg_app', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagepost',
            name='user_likes',
            field=models.ManyToManyField(related_name='liked_posts', to='log_reg_app.User'),
        ),
    ]
